# -*- mode: ruby -*-
# vi: set ft=ruby :

$NET_PREFIX     = "172.16.124"
$BRIDGE_IF      = "vmnet1"
$DC_IP          = "#{$NET_PREFIX}.50"
$DEV_IP         = "#{$NET_PREFIX}.51"
$BASE_BOX       = "windows-2016"
$CORE_BOX       = "windows-2016-core"

Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.boot_timeout = 300
  config.vm.synced_folder "../iso-images", "/isoimages"
  config.vm.synced_folder "../scripts", "/scripts"

  # Domain controller setup
  config.vm.define "dc01" do |config|
    config.vm.box = $CORE_BOX
    config.vm.hostname = "dc01"
    config.vm.network "public_network", bridge: $BRIDGE_IF, ip: $DC_IP
      
    config.vm.provider "vmware_fusion" do |fusion|
      fusion.vmx["memsize"] = "1024"
      fusion.vmx["numvcpus"] = "1"
      fusion.vmx["ethernet0.pcislotnumber"] = "33"
      fusion.fmx["ethernet0.virtualdev"] = "vmxnet3"
      fusion.fmx["ethernet1.virtualdev"] = "vmxnet3"
    end

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1
    end

    config.vm.provider 'hyperv' do |hv|
      hv.ip_address_timeout = 240
      hv.memory = 1024
    end

    config.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
    end
    
  end

  #Developer machine - VS2017 setup
  config.vm.define "devEnt" do |config|  
    config.vm.box = $BASE_BOX
    config.vm.hostname = "dev01"
    config.vm.network "public_network", bridge: $BRIDGE_IF, ip: $DC_IP

    config.vm.provider "vmware_fusion" do |fusion|
      fusion.vmx["memsize"] = "8192"
      fusion.vmx["numvcpus"] = "4"
      fusion.vmx["ethernet0.pcislotnumber"] = "33"
      fusion.fmx["ethernet0.virtualdev"] = "vmxnet3"
      fusion.fmx["ethernet1.virtualdev"] = "vmxnet3"
      fusion.linked_clone = false
    end

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
    end

    config.vm.provider 'hyperv' do |hv|
      hv.ip_address_timeout = 240
      hv.memory = 8192
    end

    config.vm.provider :libvirt do |domain|
      domain.memory = 8182
      domain.cpus = 4
    end

    config.vm.provision :shell, :path => "../scripts/install-basic-tools.ps1"
   
  end
end
