& ..\isoimages\mu_visual_studio_enterprise_2017_x86_x64_10049783.exe `
--layout C:\isoimages\vs2017_offline\enterprise `
--lang en-US `
--includeRecommended `
--add Microsoft.VisualStudio.Workload.Azure `
--add Microsoft.VisualStudio.Workload.Data `
--add Microsoft.VisualStudio.Workload.NetCoreTools `
--add Microsoft.VisualStudio.Workload.NetWeb `
--add Microsoft.VisualStudio.Workload.Node `
--add Microsoft.Net.Component.4.6.2.SDK `
--add Microsoft.Net.Component.4.6.2.TargetingPack `
--add Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools `
--add Microsoft.VisualStudio.Component.FSharp