---
driver:
  communicator: winrm
  forward_agent: yes
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 4096
  network:
  - ["forwarded_port", {guest: 5985, host: 5985}]

transport:
  name: winrm
  password: vagrant
  username: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[win-templates::default]
    attributes:
