---
driver:
  communicator: winrm
  forward_agent: yes
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 4096

transport:
  name: winrm
  password: vagrant
  username: vagrant
  elevated: true

provisioner:
  name: chef_solo

platforms:
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[win-templates::default]
      - recipe[win-templates::disable_sam_notifications]
      - recipe[win-templates::disable_UAC]
      - recipe[win-templates::disable_shutdown_tracker]
      - recipe[win-templates::enable_net35]
      - recipe[win-templates::show_hiddenFiles]
      - recipe[win-templates::show_extensions]
      - recipe[win-templates::enable_containers]
      - recipe[win-templates::enable_docker]
    attributes:
