name 'win-templates'
maintainer 'Robert Elsner'
maintainer_email 'digicoder@gmail.com'
license 'all_rights'
description 'Resources run during packer builds'
long_description 'Resources run during packer builds'
version '0.1.0'

depends 'windows'
depends 'wsus-client'